- hosts: localhost
  connection: local
  gather_facts: yes
  become: false

  tasks:
    - name: Get current user
      command: whoami
      register: whoami_output
      tags:
        - minimal

    - name: Set ansible_user to the result of whoami
      set_fact:
        ansible_user: "{{ whoami_output.stdout }}"

    - name: Update Homebrew
      command: brew update
      when: ansible_facts['os_family'] == 'Darwin'
      tags:
        - minimal
        - update

    - name: Install zsh
      package:
        name: zsh
        state: present
      tags:
        - minimal
        - zsh

    # - name: Change shell to zsh
    #   become: true
    #   shell: chsh -s /opt/homebrew/bin/zsh "{{ansible_user}}"
    #   args:
    #     executable: /bin/bash
    #   tags:
    #     - minimal
    #     - zsh

    - name: Check if Oh My Zsh is installed
      stat:
        path: ~/.oh-my-zsh
      register: oh_my_zsh
      tags:
        - minimal

    - name: Check if Oh My Zsh is installed debug
      debug: 
        msg: Does oh my zsh exist {{oh_my_zsh.stat.exists}}

    - name: Install oh-my-zsh
      shell: curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
      when: not oh_my_zsh.stat.exists
      tags: 
        - zsh
        - minimal

    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "{{ ansible_user_dir }}/.oh-my-zsh/plugins/zsh-autosuggestions"
      tags:
        - zsh
        - minimal

    - name: Install nodejs and npm
      package:
        name: ['nodejs', 'npm']
        state: present
      when: ansible_facts['os_family'] == 'Debian'
      tags:
        - node
        - minimal

    - name: Install nodejs and npm
      package: 
        name: node 
        state: present
      tags:
        - node
        - minimal

    - name: Install n
      command: npm install -g n
      tags:
        - node
        - minimal

    - name: Install node version 20
      become: true
      shell: n 20
      tags:
        - node
        - minimal

    - name: Install tmux
      package:
        name: tmux
        state: present
      tags:
        - tmux
        - minimal

    - name: Install nvim
      package:
        name: nvim
        state: present
      tags:
        - nvim
        - minimal

    - name: Install prettier 
      package:
        name: prettier 
        state: present
      tags:
        - prettier 
        - formatter 
        - nvim 

    - name: Install stow
      package:
        name: stow
        state: present
      tags:
        - stow
        - minimal

    - name: Install blueutil 
      package:
        name: blueutil 
        state: present
      tags:
        - blueutil 
        - audio 

    - name: Install switchaudio-osx 
      package:
        name: switchaudio-osx 
        state: present
      tags:
        - switchaudio-osx 
        - audio

    - name: Install fzf
      package:
        name: fzf
        state: present
      tags:
        - fzf
        - minimal

    - name: Install ripgrep
      package:
        name: ripgrep 
        state: present
      tags:
        - ripgrep 
        - minimal

    - name: Install cask kitty
      community.general.homebrew_cask:
        name: kitty
        state: present
      tags:
        - kitty

    - name: Install cask microsoft-edge
      community.general.homebrew_cask:
        name: microsoft-edge 
        state: present
      tags:
        - microsoft-edge 
        - browsers

    - name: Install cask firefox
      community.general.homebrew_cask:
        name: firefox
        state: present
      tags:
        - firefox
        - browsers

    - name: Install cask amethyst
      community.general.homebrew_cask:
        name: amethyst 
        state: present
      tags:
        - amethyst 
        - wm

    - name: Install cask shortcat
      community.general.homebrew_cask:
        name: shortcat 
        state: present
      tags:
        - shortcat 
        - wm

    - name: Install brave-browser
      community.general.homebrew_cask:
        name: brave-browser 
        state: present
      tags:
        - brave-browser 

    - name: Install cask deepl
      community.general.homebrew_cask:
        name: deepl 
        state: present
      tags:
        - deepl 

    - name: Install cask bartender
      community.general.homebrew_cask:
        name: bartender 
        state: present
      tags:
        - bartender 

